// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'firebase_options.dart';

import 'package:firebase_core_platform_interface/firebase_core_platform_interface.dart';

//show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions /*web = FirebaseOptions*/ (
        apiKey: 'AIzaSyALz5kduBK33nKCHx64LTQrMsZhCTn5fSo',
        appId: '1:819760134450:web:84ec230cba0c93bb7b3f2b',
        messagingSenderId: '819760134450',
        projectId: 'flutter-test-app-493b2',
        authDomain: 'flutter-test-app-493b2.firebaseapp.com',
        storageBucket: 'flutter-test-app-493b2.appspot.com',
      );
    }
  }
}
/*
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALz5kduBK33nKCHx64LTQrMsZhCTn5fSo',
    appId: '1:819760134450:web:84ec230cba0c93bb7b3f2b',
    messagingSenderId: '819760134450',
    projectId: 'flutter-test-app-493b2',
    authDomain: 'flutter-test-app-493b2.firebaseapp.com',
    storageBucket: 'flutter-test-app-493b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBphYYu0FbclZfoG1SmUFvCqmOGgTlbL-Q',
    appId: '1:819760134450:android:6b396ff8445538937b3f2b',
    messagingSenderId: '819760134450',
    projectId: 'flutter-test-app-493b2',
    storageBucket: 'flutter-test-app-493b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8souNoBYKlVWiOB0okD-ojh01S_jaMs4',
    appId: '1:819760134450:ios:ea2e00028a6074937b3f2b',
    messagingSenderId: '819760134450',
    projectId: 'flutter-test-app-493b2',
    storageBucket: 'flutter-test-app-493b2.appspot.com',
    iosClientId:
        '819760134450-8ic0kksdobccfc14utvharrjo573283a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8souNoBYKlVWiOB0okD-ojh01S_jaMs4',
    appId: '1:819760134450:ios:ea2e00028a6074937b3f2b',
    messagingSenderId: '819760134450',
    projectId: 'flutter-test-app-493b2',
    storageBucket: 'flutter-test-app-493b2.appspot.com',
    iosClientId:
        '819760134450-8ic0kksdobccfc14utvharrjo573283a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );
}
*/